eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL}:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}

spring:
  cloud:
    gateway:
      routes:
      - id: viaandina-scheduler-msvc
        uri: lb://viaandina-scheduler-msvc
        predicates:
        - Path=/api/scheduler/**
        filters:
        - StripPrefix=2