spring:
  application:
    name: viaandina-gateway-server
  profiles:
    active: local
  cloud:
      gateway:
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
                - "http://localhost:4200"
                - "http://localhost:4300"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders:
                - "*"
              allowCredentials: true

server:
  port: 8090
