eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}

spring:
  cloud:
    gateway:
      routes:
      - id: viaandina-scheduler-msvc
        uri: lb://viaandina-scheduler-msvc
        predicates:
        - Path=/api/scheduler/**
        filters:
        - StripPrefix=2
      - id: viaandina-fleet-management-msvc
        uri: lb://viaandina-fleet-management-msvc
        predicates:
        - Path=/api/fleet/**
        filters:
        - StripPrefix=2